apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: vault-auth
spec:
  template:
    metadata:
      name: 'vault-auth-{{ name }}'
    spec:
      project: default
      source:
        repoURL: https://github.com/bradfordwagner/vault.k8s.sharedsecrets
        targetRevision: HEAD
        path: charts/vault.auth
        helm:
          releaseName: vault-auth
          values: |
            service_account_name: vault-auth
      destination:
        name: '{{ name }}'
        namespace: vault-auth
      syncPolicy:
        automated:
          prune: true
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
